# Generated by Django 4.1 on 2022-08-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
