# Generated by Django 4.1 on 2022-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0004_remove_snack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
