# Generated by Django 4.1 on 2022-08-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0006_alter_snack_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='description',
        ),
    ]
