# Generated by Django 4.1 on 2022-08-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0007_remove_snack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
    ]
